### Lesson1


### Тема “Вычисления с помощью Numpy”

### Задание 1

In [3]:
import numpy as np

In [17]:
a = np.array([[1, 6], [2, 8], [3, 11], [3, 10], [1, 7]])
a


array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [18]:
mean_a = a.mean(axis=0)
mean_a


array([2. , 8.4])

### Задание 2

In [21]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Задание 3

In [22]:
a_centered_sp = a_centered[:, 0] @ a_centered[:, 1]
a_centered_sp

8.0

In [23]:
test_cov = a_centered_sp / (a.shape[0] - 1)
test_cov

2.0

### Задание 4

In [24]:
cov = np.cov(a.T)[0, 1]
cov

2.0

### Тема “Работа с данными в Pandas”

### Задание 1

In [25]:
import pandas as pd

In [26]:
authors = pd.DataFrame({'author_id' : [1, 2, 3], 'author_name' : ['Тургенев', 'Чехов', 'Островский']})
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [27]:
book = pd.DataFrame({'author_id' : [1, 1, 1, 2, 2, 3, 3], 
                     'book_title' : ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 
                                                 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
                     'price' : [450, 300, 350, 500, 450, 370, 290]})
book

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

### Задание 2

In [28]:
authors_price = pd.merge(authors, book, on='author_id')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

### Задание 3

In [29]:
top5 = authors_price.sort_values(by="price", ascending=False, inplace=False).head()
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

### Задание 4

In [30]:
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

In [44]:
authors_stat = pd.DataFrame({'author_name' : authors_price['author_name'].unique(),
                             'min_price' : authors_price.groupby('author_name', sort=False)['price'].min(),
                             'max_price' : authors_price.groupby('author_name', sort=False)['price'].max(),
                             'mean_price' : authors_price.groupby('author_name', sort=False)['price'].mean()})
authors_stat.style.hide(axis ='index')

In [36]:
authors_stat.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, Тургенев to Островский
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   author_name  3 non-null      object 
 1   min_price    3 non-null      int64  
 2   max_price    3 non-null      int64  
 3   mean_price   3 non-null      float64
dtypes: float64(1), int64(2), object(1)
memory usage: 120.0+ bytes
